djangoproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('pages.urls')),
    path("", include('records.urls')),
    path("", include("users.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path
from .views import IndexView, AboutView

urlpatterns = [
    # path('endereço/', view.as_view(), name='nome-da-url'),
    path('', IndexView.as_view(), name='index'),
    path('sobre/', AboutView.as_view(), name='about'),
]

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import UserCreate, UpdateProfile

urlpatterns = [
    # path('endereço/', view.as_view(), name='nome-da-url'), 
    path('login/', auth_views.LoginView.as_view(
        template_name = "users/login.html"    
    ), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('cadastrar/', UserCreate.as_view(), name='add-user'),
    path('editarDados/', UpdateProfile.as_view(), name='edit-profile'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MinLengthValidator

# Create your models here.
class Profile(models.Model):
    complet_name = models.CharField(max_length=100, verbose_name='Nome Completo',  null=True)
    cpf = models.CharField(max_length=14, validators=[MinLengthValidator(14)], verbose_name='CPF',  null=True)
    phone =  models.CharField(max_length=16, validators=[MinLengthValidator(14)],verbose_name='Telefone',  null=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    
    def __str__(self):
        return "{} - ({})".format(self.complet_name, self.cpf)
    

users/forms.py
from django import forms
from django.contrib.auth.models import User, Group
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import get_object_or_404
from django.core.exceptions import ValidationError

class UserForm(UserCreationForm):
    email = forms.EmailField(max_length=100)
    
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2' ]
        
    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email = email).exists():
            raise ValidationError("O email {} já está em uso.".format(email))
        return email
            
        
        
            
        

users/views.py
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView, UpdateView
from django.contrib.auth.models import User, Group
from .forms import UserForm
from django.shortcuts import get_object_or_404
from .models import Profile

class UserCreate(CreateView):
    template_name = 'records/form.html'
    model = User
    form_class = UserForm
    success_url = reverse_lazy('index')
    
    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['header'] = 'Cadastro de Usuário'
        return context
    
    def form_valid(self, form):
        group = get_object_or_404(Group, name='Docente')
        url = super().form_valid(form)
        self.object.groups.add(group)
        self.object.save()
        Profile.objects.create(user=self.object)
        return url
    
class UpdateProfile(UpdateView):
    template_name = "users/update_form.html"
    model = Profile
    fields = ["complet_name", "cpf", "phone"]
    success_url = reverse_lazy('index')
    
    def get_object(self, queryset=None):
        self.object = get_object_or_404(Profile, user = self.request.user)
        return self.object
    
    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['header'] = 'Editar Perfil'
        return context

users/templates/users/form.html
{% extends 'pages/base.html' %}

{% load static %}

{% load crispy_forms_tags %}

{% block stylesheet %}
<link rel="stylesheet" href="{% static 'css/login.css' %}" >
{% endblock %}

{% block title %}
<title>Login</title>
{% endblock%}

{% block navbar %}
{% endblock%}

{% block content %}
    <div class="m-auto mb w-75 p-2 rounded-4">
        <div class="m-2">
            <h3>Login</h3>
            <p>Preencha os campos para entrar no sistema.</p>
        </div>
        
        <hr>
    
        <form class="m-2" method="POST" action="">
    
            {% csrf_token %}
    
            <div class="row">
                {{ form|crispy }}
            </div>
    
            <button type="submit" class="btn btn-primary" >Entrar</button>
        </form>
       </div>
{% endblock%}

users/templates/users/login.html
{% extends 'pages/base.html' %}

{% load static %}

{% load crispy_forms_tags %}

{% block stylesheet %}
<link rel="stylesheet" href="{% static 'css/login.css' %}" >
{% endblock %}

{% block title %}
<title>Login</title>
{% endblock%}


{% block navbar %}
{% endblock%}

{% block content %}
{% if request.user.is_authenticated %}
    <h3>
        Ação não permitida.
    </h3>
    <p>Você não faz parte do grupo que pode utilizar essa funcionalidade</p>
    <hr>
    <a onclick="history.back()" class="btn btn-primary">Voltar</a>
{%else%}
    <div class="m-auto mb w-75 p-2 rounded-4">
        <div class="m-2">
            <h3>Login</h3>
            <p>Preencha os campos para entrar no sistema.</p>
        </div>
        
        <hr>
        
        <form class="m-2" method="POST" action="">
    
            {% csrf_token %}
    
            <div class="row">
                {{ form|crispy }}
            </div>
    
            <button type="submit" class="btn btn-primary" >Entrar</button>
        </form>
       </div>
{% endif %}
{% endblock%}

users/templates/users/update_form.html
{% extends 'pages/base.html' %}

{% load static %}

{% load crispy_forms_tags %}

{% block stylesheet %}
<link rel="stylesheet" href="{% static 'css/login.css' %}" >
{% endblock %}

{% block title %}
<title>Login</title>
{% endblock%}

{% block content %}
    <div class="m-auto mb w-75 p-2 rounded-4">
        <div class="m-2">
            <h3>Meu Dados Pessoais</h3>
            <p>Atualize as informações do seu perfil</p>
        </div>
        
        <hr>
    
        <form class="m-2" method="POST" action="">
    
            {% csrf_token %}
    
            <div class="row">
                {{ form|crispy }}
            </div>
    
            <button type="submit" class="btn btn-primary" >Entrar</button>
        </form>
       </div>
{% block scripts %}
<script src="{% static 'js/jquery.mask.min.js' %}"></script>
<script>

    $(document).ready(function(){
        $("#id_cpf").mask("000.000.000-00");

        var SPMaskBehavior = function (val) {
            return val.replace(/\D/g, '').length === 11 ? '(00) 00000-0000' : '(00) 0000-00009';
          },
          spOptions = {
            onKeyPress: function(val, e, field, options) {
                field.mask(SPMaskBehavior.apply({}, arguments), options);
              }
          };
          
          $('#id_phone').mask(SPMaskBehavior, spOptions);
    });

</script>
{% endblock %}
{% endblock%}